permalink: /:year/:month/:day/:title
paginate: 10
exclude: ["Makefile", "LICENSE.txt", "less", "NOTES.txt", "inscriptions_2012_05_31.ods", "logo_twitter.png", "svg", "draft", "docs", "interviews"]
title: LoOPS
url: http://reseau-loops.github.io
encoding: utf-8
markdown: rdiscount
name: Réseau LoOPS
description: Réseau des développeurs de l'Enseignement Supérieur et la Recherche - Zone Paris-Sud
